spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.phone.number=${TWILIO_PHONE}
twilio.phone.destination=${TWILIO_DESTINATION}

# ADMIN CONFIGURATION
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}
app.admin.surname=${ADMIN_SURNAME}
app.admin.mobile=${ADMIN_MOBILE}

#SERVER CONFIG AND SECURITY
server.servlet.session.timeout=PT5M
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.max-age=-1

# GMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# RECAPTCHA CONFIG
google.recaptcha.secret=${RECAPTCHA_SECRET}
google.recaptcha.site=${RECAPTCHA_SITE}
google.recaptcha.url=https://www.google.com/recaptcha/api/siteverify

cron.secret.token=${CRON_SECRET}
app.security.mfa-secret=${MFA_SECRET}
app.security.rate-limit.capacity=6
app.security.rate-limit.refill-tokens=6

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.mvc.throw-exception-if-no-handler-found=true